---
name: Build and Deploy webapp

env:
  #Artifact Name: csye6225-webapp-${{github.run_number}}.zip
  ARTIFACT_NAME: csye6225-webapp-${{github.run_number}}.zip
  CODEDEPLOY_APPLICATION_NAME: mywebapp
  CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP_NAME: mywebapp
  AWS_REGION: us-west-2

on:
  pull_request:
      branches: [ main ]

jobs:
  ci_cd:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with: 
          java-version: 1.8
      - name: Build with maven
        run: |
          sudo su
          # echo "${{env.ARTIFACT_NAME}}"
          echo export DB_HOSTNAME=csye6225.c02nl79rv62h.us-west-2.rds.amazonaws.com >> /etc/environment
          # echo export DB_PORT=3306 >> /etc/environment
          # echo export DB_DATABASE=csye6225 >> /etc/environment
          # echo export DB_USER=csye6225 >> /etc/environment
          # echo export DB_PASS=csye6225 >> /etc/environment
          # echo export aws_access_key_id=AKIARSRCF6UBSLKMORCF >> /etc/environment
          # echo export aws_secret_access_key=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 >> /etc/environment
          # echo export aws_region=us-west-2 >> /etc/environment
          # echo export aws_bucket_name=q3mv7.prod.domain.tld20211031180936427300000001 >> /etc/environment
          # source /etc/environment
          cat /etc/environment
          exit
          # pwd
          # ls
          # mvn clean
          # mvn clean install
          # pwd
          # ls
      - name: Build Deployemnt Artifact
        run: |
          mkdir codedeploy_artifact
          zip -r ${{env.ARTIFACT_NAME}} codedeploy_artifact/
          ls
          pwd
          cd codedeploy_artifact
          pwd
          ls
          cd .. 
          pwd
          ls
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
          aws-region: ${{secrets.AWS_REGION}}
