on:
  pull_request:
      branches: [ main ]

name: Check


jobs:
  check:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run tests
      run: |
        mvn -Dtest=AmiWebapp1ApplicationTests test